### ISSUE TITLE
Launch swagger editor with disableNewUserIntro = true

### ISSUE THREAD

**Issue by Helmsdown** [borisirota/swagger-editor-server#1]
Would you consider updating your config.json to set disableNewUserIntro=true. When you launch the tool via swagger-editor-server you always get the introduction screen.

https://github.com/swagger-api/swagger-editor/blob/master/docs/config.md#disablenewuserintro

**Comment by borisirota** [comment]
@Helmsdown Its a new option I wasn't aware of when implementing it. Thanks :)

**Comment by borisirota** [comment]
@Helmsdown I forgot to update npm. Now the updated version on npm.
