### ISSUE TITLE
NPM 3 installs swagger-editor to a different location

### ISSUE THREAD

**Issue by stevehipwell** [borisirota/swagger-editor-server#2]
After upgrading node to a version that uses NPM 3 this no longer works as the _swagger-editor_ dependency is installed flat.

My suggestion would be to add _swagger-editor_ as a peer dependency, this way it would always be top level and then the path could be modified to reflect this. Otherwise a configuration parameter to set the location of _swagger-editor_ is required.

**Comment by borisirota** [comment]
@stevehipwell  thanks for your issue. I updated the code as you suggested and published to NPM. As I'm not currently using it and not NPM 3, please let me know if there are issues with the update.
