### ISSUE TITLE
How to run and use swagger-editor-server

### ISSUE THREAD

**Issue by Jaxon-Wei** [borisirota/swagger-editor-server#3]
sorry, i am not good at nodejs, so could you tell me how to run and use swagger-editor-server?
thank you

**Comment by borisirota** [comment]
It is explained in the [README](https://github.com/borisirota/swagger-editor-server/blob/master/README.md):

``` javascript
    var editor = require("swagger-editor-server");
    editor.edit(swaggerFile); // the path to the swagger api file
```

Closing it for now. Please reopen if you have any other questions.
